// Mock Data Repository for Demo Account (100% DB-Free Showcase)

export const DEMO_SESSIONS = [
  {
    id: 'demo-session-1',
    title: 'Manhattan WMS Architecture & Warehouse Automation',
    platform: 'Manhattan WMS',
    trainer: 'Arul Xavier (Lead Consultant)',
    participantsCount: 14,
    currentlyParticipating: 12,
    date: new Date('2026-09-10T10:00:00Z').toISOString(),
    time: '10:00 AM - 01:00 PM IST',
    location: 'Online Sandbox + Teams',
    status: 'In Progress',
    quarter: 'Q3',
    trainerTotalCost: 35000,
    trainerAmountPaid: 25000,
    trainerAmountDue: 10000,
    participants: [
      { id: 'dp-1', participantName: 'Alex Mercer (WMS Lead)', amountDue: 15000, amountPaid: 15000, paymentStatus: 'PAID' },
      { id: 'dp-2', participantName: 'Samantha Reed (Logistics Mgr)', amountDue: 15000, amountPaid: 10000, paymentStatus: 'PARTIAL' },
      { id: 'dp-3', participantName: 'David Vance (Warehouse Sup)', amountDue: 12000, amountPaid: 12000, paymentStatus: 'PAID' },
      { id: 'dp-4', participantName: 'Priya Sharma (Supply Chain Analyst)', amountDue: 12000, amountPaid: 12000, paymentStatus: 'PAID' },
      { id: 'dp-5', participantName: 'Kevin Lin (Systems Admin)', amountDue: 12000, amountPaid: 0, paymentStatus: 'PENDING' },
    ],
  },
  {
    id: 'demo-session-2',
    title: 'Blue Yonder Demand Planning & Luminate AI Sandbox',
    platform: 'Blue Yonder',
    trainer: 'Senior Supply Chain Specialist',
    participantsCount: 12,
    currentlyParticipating: 10,
    date: new Date('2026-09-05T02:00:00Z').toISOString(),
    time: '02:00 PM - 05:00 PM IST',
    location: 'Interactive BY Cloud Lab',
    status: 'Completed',
    quarter: 'Q3',
    trainerTotalCost: 28000,
    trainerAmountPaid: 28000,
    trainerAmountDue: 0,
    participants: [
      { id: 'dp-6', participantName: 'Michael Chang (Demand Planner)', amountDue: 14000, amountPaid: 14000, paymentStatus: 'PAID' },
      { id: 'dp-7', participantName: 'Elena Rostova (Inventory Specialist)', amountDue: 14000, amountPaid: 14000, paymentStatus: 'PAID' },
      { id: 'dp-8', participantName: 'James Wright (SCM Manager)', amountDue: 14000, amountPaid: 14000, paymentStatus: 'PAID' },
    ],
  },
  {
    id: 'demo-session-3',
    title: 'Kinaxis RapidResponse Supply Chain Control Tower',
    platform: 'Kinaxis',
    trainer: 'Arul Xavier',
    participantsCount: 10,
    currentlyParticipating: 9,
    date: new Date('2026-08-28T09:00:00Z').toISOString(),
    time: '09:00 AM - 12:00 PM IST',
    location: 'Kinaxis Authoring Sandbox',
    status: 'Completed',
    quarter: 'Q3',
    trainerTotalCost: 30000,
    trainerAmountPaid: 20000,
    trainerAmountDue: 10000,
    participants: [
      { id: 'dp-9', participantName: 'Robert Vance (Planning Dir)', amountDue: 18000, amountPaid: 18000, paymentStatus: 'PAID' },
      { id: 'dp-10', participantName: 'Sophia Chen (Control Tower Lead)', amountDue: 18000, amountPaid: 18000, paymentStatus: 'PAID' },
      { id: 'dp-11', participantName: 'Daniel Kim (Operations Mgr)', amountDue: 16000, amountPaid: 8000, paymentStatus: 'PARTIAL' },
    ],
  },
  {
    id: 'demo-session-4',
    title: 'SAP S/4HANA Enterprise Logistics & MM Integration',
    platform: 'SAP S/4HANA',
    trainer: 'SAP Certified Principal',
    participantsCount: 16,
    currentlyParticipating: 15,
    date: new Date('2026-08-15T11:00:00Z').toISOString(),
    time: '11:00 AM - 02:00 PM IST',
    location: 'SAP S/4HANA Live Instance',
    status: 'Completed',
    quarter: 'Q3',
    trainerTotalCost: 40000,
    trainerAmountPaid: 40000,
    trainerAmountDue: 0,
    participants: [
      { id: 'dp-12', participantName: 'Tariq Al-Mansoor (ERP Lead)', amountDue: 20000, amountPaid: 20000, paymentStatus: 'PAID' },
      { id: 'dp-13', participantName: 'Laura Martinez (MM Consultant)', amountDue: 20000, amountPaid: 20000, paymentStatus: 'PAID' },
      { id: 'dp-14', participantName: 'Chris Evans (Procurement Head)', amountDue: 20000, amountPaid: 20000, paymentStatus: 'PAID' },
    ],
  },
];

export const DEMO_FINANCE_ANALYTICS = {
  summary: {
    totalIncome: 485000,
    totalExpenses: 145000,
    netProfit: 340000,
    totalTransactions: 24,
  },
  expensesByCategory: [
    { name: 'Trainer Fees', value: 93000, color: '#818cf8' },
    { name: 'Cloud Sandbox Servers', value: 27000, color: '#22d3ee' },
    { name: 'Marketing & Ad Spend', value: 15000, color: '#fb7185' },
    { name: 'Operations & Zoom', value: 10000, color: '#fbbf24' },
  ],
  recentTransactions: [
    { id: 'dt-1', type: 'INCOME', category: 'Tuition Fee', amount: 45000, description: 'Batch #1 Tuition Payment - Alex Mercer & Team', date: '2026-09-12' },
    { id: 'dt-2', type: 'EXPENSE', category: 'Trainer Fee', amount: 25000, description: 'Trainer Disbursal - Manhattan WMS Batch #1', date: '2026-09-11' },
    { id: 'dt-3', type: 'INCOME', category: 'Tuition Fee', amount: 42000, description: 'Blue Yonder Batch #2 Full Tuition Collection', date: '2026-09-08' },
    { id: 'dt-4', type: 'EXPENSE', category: 'Cloud Server', amount: 12000, description: 'Kinaxis Sandbox AWS Instance Monthly Fee', date: '2026-09-04' },
  ],
};

export const DEMO_COMMS_CHATS = [
  {
    id: 'demo-chat-1',
    name: 'Alex Smith (WMS Lead)',
    phone: '+1 (555) 234-5678',
    lastMessage: 'Thanks for sending the Manhattan WMS Sandbox access details!',
    timestamp: '10:42 AM',
    unreadCount: 0,
    messages: [
      { id: 'm1', sender: 'them', text: 'Hi GapAnchor team! Is registration open for the Manhattan WMS batch?', time: '10:30 AM' },
      { id: 'm2', sender: 'me', text: 'Hello Alex! Yes, registration is active. I have reserved your seat.', time: '10:35 AM' },
      { id: 'm3', sender: 'them', text: 'Thanks for sending the Manhattan WMS Sandbox access details!', time: '10:42 AM' },
    ],
  },
  {
    id: 'demo-chat-2',
    name: 'Sarah Jenkins (SCM Mgr)',
    phone: '+91 98765 43210',
    lastMessage: 'Could you share the course syllabus for Blue Yonder Demand Planning?',
    timestamp: 'Yesterday',
    unreadCount: 1,
    messages: [
      { id: 'm4', sender: 'them', text: 'Could you share the course syllabus for Blue Yonder Demand Planning?', time: 'Yesterday' },
    ],
  },
];

export const DEMO_ENQUIRIES = [
  {
    id: 'demo-enq-1',
    participantName: 'Alex Mercer',
    email: 'alex.mercer@enterprise.com',
    phone: '+1 (555) 234-5678',
    courseInterest: 'Manhattan WMS',
    stage: 'ENROLLED',
    source: 'Outlook Enquiry',
    notes: 'Paid full tuition fee. Added to Batch #1 sandbox.',
    createdAt: new Date('2026-09-01').toISOString(),
  },
  {
    id: 'demo-enq-2',
    participantName: 'Samantha Reed',
    email: 'samantha.r@logistics-corp.com',
    phone: '+1 (555) 876-5432',
    courseInterest: 'Blue Yonder',
    stage: 'DEMO_SCHEDULED',
    source: 'WhatsApp',
    notes: 'Demo scheduled for Friday 3 PM IST.',
    createdAt: new Date('2026-09-03').toISOString(),
  },
];
